apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-18-fastfood-backend
  labels:
    app: group-18-fastfood-backend
spec:
  selector:
    matchLabels:
      app: group-18-fastfood-backend
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: group-18-fastfood-backend
      labels:
        app: group-18-fastfood-backend
    spec:
      containers:
      - name: group-18-fastfood-backend
        image: tech-challenge-go
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /customers
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
        readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
        resources:
          requests:
            cpu: 1m
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: configmap-group-18-fastfood-backend
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-group-18-fastfood-backend
                key: POSTGRES_HOST
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-group-18-fastfood-backend
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-group-18-fastfood-backend
                key: POSTGRES_PASSWORD