apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: group-18-fastfood-backend-hpa
  labels:
    app: group-18-fastfood-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: group-18-fastfood-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
